config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:edit, :update, :index]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord

  validates :name, presence: true

  has_many :messages
  has_many :members
  has_many :users, through: :members

  def show_last_message
    if (last_message = messages.last).present?
      last_message.body? ? last_message.body : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end

end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :body, presence: true, unless: :image?

  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :members
  has_many :groups, through: :members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :set_group, only: [:edit, :update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to root_path, notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json { @new_messages = @messages.where('id > ?', params[:message][:id]) }
    end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group) }
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = "メッセージを入力してください。"
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(users_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
  def users_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, "グループ名", class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat-group-form__input', placeholder: 'グループ名を入力してください。'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      .chat-group-users
        - group.users.each do |user|
          .chat-group-user
            .chat-group-user__name
              = f.hidden_field :user_ids, name: "group[user_ids][]", value: user.id
              = user.name
            %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
              削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "登録する", class: "chat-group-form__action-btn"

app/views/groups/_side_bar.html.haml
.sidebar
  .user-info
    %p
      = current_user.name
    %ul.lists
      %li.list
        = link_to new_group_path do
          = fa_icon "edit", class: 'icon'
      %li.list
        = link_to edit_user_path(current_user) do
          = fa_icon "cog", class: 'icon'

  .groups
    - current_user.groups.each do |group|
      = link_to group_messages_path(group) do
        .group
          .group__name
            = group.name
          .group__message
            = group.show_last_message

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render 'form', { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render "side_bar"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_flash.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/_group.html.haml
- current_user.groups.each do |group|
  = link_to group_messages_path(group) do
    .group
      .group__name
        = group.name
      .group__message
        = group.show_last_message

app/views/messages/_header-group.html.haml
.header__group
  .header__group--name
    = @group.name
  .header__group--members
    Member:
    - @group.users.each do |user|
      = user.name
.header__edit-button
  = link_to edit_group_path(@group) do
    Edit

app/views/messages/_input.html.haml
.footer__input
  = form_for [@group, @message] do |f|
    = f.text_field :body, class: "footer__input--box", placeholder: "type a message"
    .footer__input__mask
      = f.label :image, class: 'footer__input__mask__image' do
        = fa_icon 'image'
        = f.file_field :image, class: 'hidden'
    = f.submit 'Send', class: "footer__input--send-button"

app/views/messages/_message.html.haml
.message{ "data-message-id": "#{message.id}"}
  .message__username
    = message.user.name
  .message__time
    = message.created_at
  .message__text
    -if message.body.present?
      = message.body
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/_user-info.html.haml
%p
  = current_user.name

%ul.lists

  %li.list
    = link_to new_group_path do
      = fa_icon "edit", class: 'icon'

  %li.list
    = link_to edit_user_path(current_user) do
      = fa_icon "cog", class: 'icon'

app/views/messages/index.html.haml
.wrapper
  .sidebar
    .user-info
      = render "user-info"
    .groups
      = render "group"

  .chat
    .header
      = render "header-group"
    .messages
      = render @messages
    .footer
      = render "input"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'